language: ruby
rvm:
- 2.0.0-p247
env:
  matrix:
  - BLOCKCHAINDOTINFO_API_URL="https://blockchain.info"
  global:
  - secure: TEwmoTilJ4HmKLN07/8DL4tpqlHAdFODJHKbQqCoYJLFfno6qNFe21pBNfgKFritDzvD6QSe6IelYGL1L5yd6b350EeonQXJzPqGLGsyIooB7YxVsAtPV/cCHXZgahZvZiPyVaocJHFarEDagFcoQYYp6p4yh1Amoc5DcvKNOsg=
  - secure: E2H+VVmaLPOPiIuNUsQpfGLPTb6zrrpjog2THedGVnyvMsZdGXhthMIxzOUDKkjHPZW6nqYMmEbusn4gkW1BhX5PHNuXEWI9/8hUN1E9NvDDmXSEfjTbPdqC76WN6rR6jmmWQ6shYyyL0cu3ZSJv4bCG38OPGw1nC1Yf99luwJE=
  - secure: vtqHlBWvdszEQd8Pzr2uxD4lkeY01erla1j6V+YRO+i75xLhdqQHX+1HqXeADqzjCn1GWYzKJ5em34P4K0s6PxJIoS8trfQJXKUXV3hXpjxSP9E32C4W0phc3v7eHOzqP2lp7IVeBcKcVafdeBvi1nxITyJ1jOwjH14xgOnZO+Y=
